const STRINGS = {
  appTitle:         { it: 'DA40NG Mass & Balance',          en: 'DA40NG Mass & Balance' },
  appSubtitle:      { it: 'Urbe Flight School',             en: 'Urbe Flight School' },
  selectAircraft:   { it: 'Seleziona Aereo',                en: 'Select Aircraft' },
  flightInfo:       { it: 'Info Volo',                      en: 'Flight Info' },
  instructor:       { it: 'Istruttore',                     en: 'Instructor' },
  student:          { it: 'Studente',                       en: 'Student' },
  date:             { it: 'Data',                           en: 'Date' },
  massCalc:         { it: 'Calcolo Masse',                  en: 'Mass Calculation' },
  station:          { it: 'Voce',                           en: 'Station' },
  arm:              { it: 'Braccio (m)',                    en: 'Arm (m)' },
  massKg:           { it: 'Massa (kg)',                     en: 'Mass (kg)' },
  momentKgm:        { it: 'Momento (kgm)',                  en: 'Moment (kgm)' },
  emptyMass:        { it: 'Peso a vuoto',                   en: 'Empty mass' },
  frontSeats:       { it: 'Sedili anteriori',               en: 'Front seats' },
  rearSeats:        { it: 'Sedili posteriori',              en: 'Rear seats' },
  stdBaggage:       { it: 'Bagagliaio standard',            en: 'Standard baggage' },
  baggageTube:      { it: 'Tubo bagagli',                   en: 'Baggage tube' },
  shortBagExt:      { it: 'Estensione bagagli corta',       en: 'Short baggage ext.' },
  fwdExtBag:        { it: 'Bagagliaio esteso ant.',         en: 'Fwd extended baggage' },
  aftExtBag:        { it: 'Bagagliaio esteso post.',        en: 'Aft extended baggage' },
  totalNoFuel:      { it: 'Totale senza carburante',        en: 'Total without fuel' },
  fuel:             { it: 'Carburante',                     en: 'Fuel' },
  fuelLiters:       { it: 'Litri',                          en: 'Liters' },
  totalWithFuel:    { it: 'Totale con carburante',          en: 'Total with fuel' },
  cgVerification:   { it: 'Verifica CG',                    en: 'CG Verification' },
  cgNoFuel:         { it: 'CG senza fuel',                  en: 'CG without fuel' },
  cgWithFuel:       { it: 'CG con fuel',                    en: 'CG with fuel' },
  takeoffMass:      { it: 'Massa T/O',                      en: 'T/O Mass' },
  margin:           { it: 'Margine',                        en: 'Margin' },
  available:        { it: 'disponibile',                    en: 'available' },
  withinLimits:     { it: 'ENTRO I LIMITI',                 en: 'WITHIN LIMITS' },
  outOfLimits:      { it: 'FUORI LIMITI',                   en: 'OUT OF LIMITS' },
  reference:        { it: 'RIFERIMENTO',                    en: 'REFERENCE' },
  enterPilotWeight: { it: 'Inserire peso pilota',           en: 'Enter pilot weight' },
  overStationLimit: { it: 'Supera il limite della stazione',en: 'Exceeds station limit' },
  fuelOverLimit:    { it: 'Carburante oltre il limite',     en: 'Fuel over limit' },
  overweight:       { it: 'Sovrappeso',                     en: 'Overweight' },
  export:           { it: 'Esporta',                         en: 'Export' },
  downloadPdf:      { it: 'Scarica PDF',                     en: 'Download PDF' },
  print:            { it: 'Stampa',                          en: 'Print' },
  lastWeighing:     { it: 'Ultima pesata',                  en: 'Last weighing' },
  cgDiagram:        { it: 'Diagramma Inviluppo CG',        en: 'CG Envelope Diagram' },
  generatedBy:      { it: 'Generato da Urbe W&B Dashboard', en: 'Generated by Urbe W&B Dashboard' },
};

let currentLang = localStorage.getItem('wb-lang') || 'it';

export function t(key) {
  const entry = STRINGS[key];
  if (!entry) return key;
  return entry[currentLang] || entry.it || key;
}

export function getLang() {
  return currentLang;
}

export function setLang(lang) {
  currentLang = lang;
  localStorage.setItem('wb-lang', lang);
}
